---
title: "Assignments"
---


## Weekly summaries (15%)

Each week for 10 weeks, you will summarize one article from the week's readings (the reading you can summarize has a {{< fa pen >}} after it in the course schedule). There are 13 weeks in the semester where you can write a summary, so you can skip some weeks. It is up to you to decide which weeks to skip. The summary must be no longer than three-quarters of a page (single-spaced, 12-point font). These summaries must be submitted on Canvas before class time *on the day the reading was assigned*.

See full instructions [here](weekly-summaries.qmd).


## Congregational visit paper (30% total) 

You will write an empirical research paper (4-6 pages, double-spaced) similar to the ones political scientists publish in academic journals. For this assignment, you will attend at least one religious service of a religious tradition or denomination other than your own and will write about how politics is (or is not) addressed, directly or indirectly, in that particular congregation. The paper will be broken down into the following parts that you will submit throughout the semester:

  1. <ins>*Front end of paper (2-3 pages, 7.5% of final grade):*</ins> This portion of the paper includes the motivation, research questions, literature review, theory, expectations, and methodology. This will be due early in the semester for you to do your best and get feedback.
  
  2. <ins>*Full draft for peer review (4-6 pages, 7.5% of final grade):*</ins> After collecting data for the paper, you will submit a full draft of the paper for peer review. Another student will provide feedback on your work and you will do the same for them.
  
  3. <ins>*Final draft (4-6 pages, 15% of final grade):*</ins> After the peer review, you will submit the final draft of the paper. I expect you will have included the feedback you received on the first portion of the paper as well as the feedback from your classmate.

- Papers must be submitted via Canvas. Late submissions will be penalized: half a point (out of 10) if turned in late but within 24 hours and one point for each 24-hour period after the due date.


## Op-ed (15%)

You will write an op-ed (600-1,200 words) on a course-related topic of your choice. Students must make a clear argument and use class material to help them organize their essays or provide context to the situation.



## Midterm and Final Exams (15% each)

There will be a midterm and final exam where you will answer three medium-length questions. Both the midterm and final exams will be in-person. These exams will assess your familiarity with the terms and theories in the religion and politics literature that we will have covered in class.


