---
title: "Week 4: The (Messy) Relationship Between Church and State (cont.)"
---

::: {.content-visible when-format="pdf"}

## Week 4 - The (Messy) Relationship Between Church and State (cont.)

:::

[//]: <> (Need to write intro)

### Tuesday, September 16

- Kruse, Kevin Michael. 2016. "'Government Under God'." In *One Nation under God: How Corporate America Invented Christian America.* New York: Basic Books. (Chapter 3) {{< fa brands dropbox title="Available on Dropbox folder" >}} {{< fa pen >}}


- *Hail Satan?*, directed by Penny Lane. 2019. Hard Working Movies/Magnolia Pictures. {{< fa film >}} (will watch in class)



### Thursday, September 18

- Hertzke, Allen D., Laura R. Olson, Kevin R. den Dulk, and Robert Booth Fowler. 2018. "Church and State in the Courts." In *Religion and Politics in America: Faith, Culture, and Strategic Choices. 6th ed.* New York, NY: Routledge. (Chapter 12) {{< fa brands dropbox title="Available on Dropbox folder" >}}


- *NPR*. June 30, 2024. "How will Louisiana's Ten Commandments classroom requirements be funded and enforced?" [{{< fa newspaper >}}](https://www.npr.org/2024/06/30/nx-s1-5024117/louisiana-ten-commandments-classroom-requirement-how-funded-and-enforced)


- Jaden Edison. July 22, 2024. "Texas' Christian-influenced curriculum spurs worries about bullying, church-state separation" *KBTX3* [{{< fa newspaper >}}](https://www.kbtx.com/2024/07/22/texas-christian-influenced-curriculum-spurs-worries-about-bullying-church-state-separation/)





 


