---
title: "Week 11: White Christians and the Religious Right"
---

::: {.content-visible when-format="pdf"}

## Week 11 - White Christians and the Religious Right

:::


[//]: <> (Need to write intro)

### Tuesday, November 4

- "The Evangelical Vote." *Throughline.* NPR. Podcast. [{{< fa podcast >}}](https://www.npr.org/2020/09/23/916048798/the-evangelical-vote})

- Jones, Robert P. 2020. "Remembering: Christianity as the Conductor of White Supremacy." *White Too Long: The Legacy of White Supremacy in American Christianity.* Simon & Schuster. (Chapter 2: pp. 25-71.) {{< fa brands dropbox title="Available on Dropbox folder" >}}

    - (Optional) Robert P. Jones and Terry Gross. *Fresh Air.* NPR. Podcast. [{{< fa podcast >}}](https://www.npr.org/2020/07/30/896712611/american-christianity-must-reckon-with-legacy-of-white-supremacy-author-says)



### Thursday, November 6

- Whitehead, Andrew L., and Samuel L. Perry. 2020. *Taking America Back for God: Christian Nationalism in the United States.* Oxford University Press. (Introduction: pp. 1-21). {{< fa brands dropbox title="Available on Dropbox folder" >}} 

- Baker, Joseph O, Samuel L Perry, and Andrew L Whitehead. 2020. "Keep America Christian (and White): Christian Nationalism, Fear of Ethnoracial Outsiders, and Intention to Vote for Donald Trump in the 2020 Presidential Election." *Sociology of Religion* 81(3): 272–93. {{< fa brands dropbox title="Available on Dropbox folder" >}} {{< fa pen >}}


::: {.content-visible when-format="html"}

### In-class readings

- PRRI. 2023. ["A Christian Nation? Understanding the Threat of Christian Nationalism to American Democracy and Culture"](https://prri.org/research/a-christian-nation-understanding-the-threat-of-christian-nationalism-to-american-democracy-and-culture/)


- PEW. 2022. ["45% of Americans Say U.S. Should Be a ‘Christian Nation’"](https://www.pewresearch.org/religion/2022/10/27/45-of-americans-say-u-s-should-be-a-christian-nation/)


:::



:::{.callout-important}

### Deadline

Final draft of Congregational Visit Paper due Sunday, November 9, at 11:59pm on Canvas

:::



