---
title: "Week 12: Religious Minorities"
---

::: {.content-visible when-format="pdf"}

## Week 12 - Religious Minorities

:::


[//]: <> (Need to write intro)

### Tuesday, November 11

- Hertzke, Allen D., Laura R. Olson, Kevin R. den Dulk, and Robert Booth Fowler. 2018. "Judaism, Islam, and Other Expressions of Religious Pluralism." *Religion and Politics in America: Faith, Culture, and Strategic Choices. 6th ed.* New York, NY: Routledge. (Chapter 4.) {{< fa file-pdf >}} 



### Thursday, November 13

- Lajevardi, Nazita. 2020. "Access Denied: Exploring Muslim American Representation and Exclusion by State Legislators." *Politics, Groups, and Identities* 8(5): 957–85. {{< fa brands dropbox title="Available on Dropbox folder" >}}

- Madrid, Raul, Jennifer L. Merolla, Aldo Yanez Ruiz, and Jean Reith Schroedel. 2022. "The Relevance of Religion for Political Office: Voter Bias Toward Candidates from Different Religious Backgrounds." *Political Behavior* 44(2): 981–1001. {{< fa brands dropbox title="Available on Dropbox folder" >}} {{< fa pen >}}



::: {.content-visible when-format="html"}

### In-class reading

- PEW. 2025. ["Religious Landscape Study."](https://www.pewresearch.org/religious-landscape-study/)


- PEW. 2025. ["Faith on the Hill: The religious composition of the 119th Congress"](https://www.pewresearch.org/religion/2025/01/02/faith-on-the-hill-2025/)

:::



:::{.callout-important}

### Deadline

Topic for op-ed due Friday, November 14, at 11:59pm on Canvas

:::


